#! python3
#Program to filter out phone numbers and e-mails from clipboard, replaces clipboard, and allows paste of only phone numbers and e-mails

import re, pyperclip

# Create a regex for phone numbers

phoneRegex = re.compile(r'''

# 415-555-0000, 555-1230, (415 555-0000, 555-0000 ext 123456, ext. 123456, x12345

(
((\d\d\d)|(\(\d\d\d\)))?        # area code (optional)
(\s|-)                          # first seperator
\d\d\d                          # first 3 digits
-                               # seperator
\d\d\d\d                        # last 4 digits
(((ext(\.)?\s)|x)               # extension word-part(optional)
 (\d{2,5}))?                    # extension number-part (optional)

)
''', re.VERBOSE)

# Create a regex for e-mail numbers

emailRegex = re.compile(r'''

# some.+_thing@something.com

[a-zA-Z0-9_.+]+     # name part, ex [a-zA-Z0-0_.+] 
@                   # @ symbol
[a-zA-Z0-9_.+]+     # domain name part

''', re.VERBOSE)

# Get the text off the clipboard

text = pyperclip.paste()

# Extract the e-mail and phone from this text

extractedPhone = phoneRegex.findall(text)
extractedEmail = emailRegex.findall(text)

allPhoneNumbers = []
for phoneNumber in extractedPhone:
    allPhoneNumbers.append(phoneNumber[0])

# Copy the extracted email and phone to the clipboard

results = '\n'.join(allPhoneNumbers) + '\n' + '\n'.join(extractedEmail)
pyperclip.copy(results)

allPhoneNumbers = []
for phoneNumber in extractedPhone:
    allPhoneNumbers.append(phoneNumber[0])
